*** Variables ***
${agentasidetabjson}    ${EMPTY}
&{AgentAsideTabSelector}    chat=selected    wait=    myknowledgebase=    mynotes=    mytickets=    myhistory=
${avatarloginstatstr}    '{"elements":[{"name":"avatarloginstatdiv","xPath":"/html/body/aside/section/div","text":{"zh_CN":"","en_US":""},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[{"name":"class","value":{"zh_CN":"em-avatar-loginstat","en_US":"em-avatar-loginstat"}}],"elements":[{"name":"namelabel","xPath":"/label","text":{"zh_CN":"%s","en_US":"%s"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]},{"name":"statul","xPath":"/ul","text":{"zh_CN":"","en_US":""},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[{"name":"class","value":{"zh_CN":"ui-cmp-modulepopuplist%s","en_US":"ui-cmp-modulepopuplist%s"}}],"elements":[{"name":"statli1","xPath":"/li[1]","text":{"zh_CN":"","en_US":""},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[{"name":"class","value":{"zh_CN":"em-avatar-loginstat-itm%s","en_US":"em-avatar-loginstat-itm%s"}}],"elements":[{"name":"statspanlabel","xPath":"/label","text":{"zh_CN":"空闲","en_US":"Online"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]},{"name":"statli2","xPath":"/li[2]","text":{"zh_CN":"","en_US":""},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[{"name":"class","value":{"zh_CN":"em-avatar-loginstat-itm%s","en_US":"em-avatar-loginstat-itm%s"}}],"elements":[{"name":"statspanlabel","xPath":"/label","text":{"zh_CN":"忙碌","en_US":"Busy"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]},{"name":"statli3","xPath":"/li[3]","text":{"zh_CN":"","en_US":""},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[{"name":"class","value":{"zh_CN":"em-avatar-loginstat-itm%s","en_US":"em-avatar-loginstat-itm%s"}}],"elements":[{"name":"statspanlabel","xPath":"/label","text":{"zh_CN":"离开","en_US":"Away"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]},{"name":"statli4","xPath":"/li[4]","text":{"zh_CN":"","en_US":""},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[{"name":"class","value":{"zh_CN":"em-avatar-loginstat-itm%s","en_US":"em-avatar-loginstat-itm%s"}}],"elements":[{"name":"statspanlabel","xPath":"/label","text":{"zh_CN":"隐身","en_US":"Invisible"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}]}]}]}'

*** Keywords ***
format avatarloginstatstr
    [Arguments]    ${name}    ${showstate}    ${onlieselected}    ${busyselected}    ${awayselected}    ${hiddenselected}
    ${s}    evaluate    ${avatarloginstatstr} % (${name},${name},${showstate},${showstate},${onlieselected},${onlieselected},${busyselected},${busyselected},${awayselected},${awayselected},${hiddenselected},${hiddenselected})
    [Return]    ${s}
