*** Variables ***
${tickethelptopicbasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/helptopic","GrayKey":"ticket","ResourceKey":"admin_tickets_helptopic"}},"elements":[{"name":"header","xPath":"//*[@id='em-helptopic']/header/h1","text":{"zh-CN":"工单帮助主题自定义","en-US":"Ticket help topics"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${ticketprioritiesbasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/priority","GrayKey":"ticket","ResourceKey":"admin_tickets_priority"}},"elements":[{"name":"header","xPath":"//*[@id='em-priority']/header/h1","text":{"zh-CN":"工单优先级自定义","en-US":"Ticket priorities"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${tickettagbasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/tag","GrayKey":"ticket","ResourceKey":"admin_tickets_tag"}},"elements":[{"name":"header","xPath":"//*[@id='em-ticket-tag']/header/h1","text":{"zh-CN":"工单标签自定义","en-US":"Ticket tags"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${ticketeventbasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/event","GrayKey":"ticket","ResourceKey":"admin_tickets_event"}},"elements":[{"name":"header","xPath":"//*[@id='em-event']/header/h1","text":{"zh-CN":"工单事件推送配置","en-US":"Ticket webhook"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${ticketemailbasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/email","GrayKey":"ticket","ResourceKey":"admin_tickets_email"}},"elements":[{"name":"header","xPath":"//*[@id='em-email']/header/h1","text":{"zh-CN":"邮箱设置","en-US":"Mailbox settings"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${ticketstatusbasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/status","GrayKey":"ticket","ResourceKey":"admin_tickets_status"}},"elements":[{"name":"header","xPath":"//*[@id='em-status']/header/h1","text":{"zh-CN":"工单状态自定义","en-US":"custom status"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${ticketslabasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/sla","GrayKey":"ticket","ResourceKey":"admin_tickets_sla"}},"elements":[{"name":"header","xPath":"//*[@id='em-sla']/header/h1","text":{"zh-CN":"SLA计划","en-US":"SLA plan"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${ticketstatisticbasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/statistic","GrayKey":"ticket","ResourceKey":"admin_tickets_statistic"}},"elements":[{"name":"header","xPath":"//*[@id='em-ticket-statistic']/header/h1","text":{"zh-CN":"工单统计","en-US":"ticket statistic"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${ticketchannelemailbasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/channelemail","GrayKey":"ticket","ResourceKey":"admin_tickets_channelemail"}},"elements":[{"name":"header","xPath":"//*[@id='em-channelemail']/header/h1","text":{"zh-CN":"邮箱渠道自定义","en-US":"custom channel email"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${ticketchannelbasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/channel","GrayKey":"ticket","ResourceKey":"admin_tickets_channel"}},"elements":[{"name":"header","xPath":"//*[@id='em-ticket-channel']/header/h1","text":{"zh-CN":"网页渠道","en-US":"channel settings"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${ticketformsbasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/forms","GrayKey":"ticket","ResourceKey":"admin_tickets_forms"}},"elements":[{"name":"header","xPath":"//*[@id='em-ticket-forms']/header/h1","text":{"zh-CN":"自定义表单","en-US":"custom form"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${ticketbasicconfigbasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/basicconfig","GrayKey":"ticket","ResourceKey":"admin_tickets_basicconfig"}},"elements":[{"name":"header","xPath":"//*[@id='em-ticket-basicconfig']/header/h1","text":{"zh-CN":"JIRA对接","en-US":"jira connect"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${ticketsatisfactionbasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/satisfaction","GrayKey":"ticket","ResourceKey":"admin_tickets_satisfaction"}},"elements":[{"name":"header","xPath":"//*[@id='em-ticket-satisfaction']/header/h1","text":{"zh-CN":"满意度评价邀请设置","en-US":"Satisfaction survey"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${tickettriggerbasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/trigger","GrayKey":"ticket","ResourceKey":"admin_tickets_trigger"}},"elements":[{"name":"header","xPath":"//*[@id='em-ticket-trigger']/header/h1","text":{"zh-CN":"触发器","en-US":"trigger"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${ticketcannedreplybasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/cannedreply","GrayKey":"ticket","ResourceKey":"admin_tickets_cannedreply"}},"elements":[{"name":"header","xPath":"//*[@id='em-ticket-cannedreply']/header/h1","text":{"zh-CN":"内容、回复模板设置","en-US":"canned content"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${ticketqualitybasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/quality","GrayKey":"ticket","ResourceKey":"admin_tickets_quality"}},"elements":[{"name":"header","xPath":"//*[@id='em-ticket-quality']/header/h1","text":{"zh-CN":"工单质检","en-US":"Quality"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
${ticketdownloadbasejson}    {"navigator":{"Admin":{"uri":"/mo/admin/ticket/tickets/ticketdownload","GrayKey":"ticket","ResourceKey":"admin_tickets_ticketdownload"}},"elements":[{"name":"header","xPath":"//*[@id='em-ticket-download']/header/h1","text":{"zh-CN":"导出管理","en-US":"Export"},"op":"show","opjson":"","GrayKey":"base","ResourceKey":"base","attributes":[],"elements":[]}]}
